# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Check for Module Updates

on:
  schedule:
    - cron: '17,47 * * * *' # Twice every hour at minute 17 and 47
  workflow_dispatch:
    inputs:
      module:
        description: 'Optional specific module to update (e.g. score_communication). If not set, all auto-update modules are checked instead.'
        required: false
        default: ''
  push:
    branches:
      - main

jobs:
  check-updates:
    if: ${{ github.event.repository.fork == false }}
    runs-on: ubuntu-latest

    # permissions must be set even when using a PAT
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: üì• Check out
        uses: actions/checkout@v6
        with:
          persist-credentials: false  # We will use a PAT instead

      - name: üïµÔ∏è‚Äç‚ôÇÔ∏è Debug PAT
        if: runner.debug
        run: |
          echo "SCORE_BOT_CLASSIC_PAT is set: [${{ secrets.SCORE_BOT_CLASSIC_PAT != '' }}]"
          echo "GITHUB_TOKEN is set: [${{ secrets.GITHUB_TOKEN != '' }}]"
        env:
          SCORE_BOT_CLASSIC_PAT: ${{ secrets.SCORE_BOT_CLASSIC_PAT }}

      - name: "üïµÔ∏è‚Äç‚ôÇÔ∏è Debug PAT: /user"
        if: runner.debug
        run: |
          curl -s -H "Authorization: token $SCORE_BOT_CLASSIC_PAT" https://api.github.com/user
        env:
          SCORE_BOT_CLASSIC_PAT: ${{ secrets.SCORE_BOT_CLASSIC_PAT }}

      - name: "üïµÔ∏è‚Äç‚ôÇÔ∏è Debug PAT: /repos/eclipse-score/bazel_registry"
        if: runner.debug
        run: |
          curl -s -H "Authorization: token $SCORE_BOT_CLASSIC_PAT" https://api.github.com/repos/eclipse-score/bazel_registry
        env:
          SCORE_BOT_CLASSIC_PAT: ${{ secrets.SCORE_BOT_CLASSIC_PAT }}

      - name: "üïµÔ∏è‚Äç‚ôÇÔ∏è Debug PAT: /user/repos"
        if: runner.debug
        run: |
          curl -s -H "Authorization: token $SCORE_BOT_CLASSIC_PAT" https://api.github.com/user/repos?per_page=100
        env:
          SCORE_BOT_CLASSIC_PAT: ${{ secrets.SCORE_BOT_CLASSIC_PAT }}

      - name: ‚öôÔ∏è Setup uv
        uses: astral-sh/setup-uv@v5
      - name: üõ†Ô∏è Setup Python Dependencies
        run: uv sync --dev

      - name: üß© Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          set -eu
          {
            printf "This PR updates the modules to their latest versions.\n"
            printf "Please review and merge if everything looks good.\n\n"
            uv run registry-manager ${{ github.event.inputs.module }}
          } | tee /tmp/output.log

      - name: üì§ Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: Update modules
          author: eclipse-score-bot <187756813+eclipse-score-bot@users.noreply.github.com>
          body-path: /tmp/output.log
          commit-message: Update modules
          base: main
          branch: bot/modules-update
          token: ${{ secrets.SCORE_BOT_CLASSIC_PAT }} # PAT belongs to eclipse-score-bot
          labels: automation
