# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Check for Module Updates

on:
  schedule:
    - cron: '0 0,12 * * *'  # Twice a day
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-updates:
    runs-on: ubuntu-latest

    # Write permissions are granted in the last step via PAT
    permissions:
      contents: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: Run version checker script
        id: check_versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r tools/requirements.txt
          python scripts/check_and_update_modules.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update modules
          author: eclipse-score-bot <187756813+eclipse-score-bot@users.noreply.github.com>
          committer: eclipse-score-bot <187756813+eclipse-score-bot@users.noreply.github.com>
          body: |
            This PR updates the modules to their latest versions.
            Please review and merge if everything looks good.
          commit-message: Update modules
          branch: bot/modules-update
        env:
          # Use token with write access.
          # Using a different token than GITHUB_TOKEN is also required,
          # in order to trigger subsequent PR-workflows.
          GITHUB_TOKEN: ${{ secrets.SCORE_BOT_PAT }}
