# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Check for Module Updates

on:
  schedule:
    - cron: '17 * * * *' # At minute 17 past every hour
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-updates:
    runs-on: ubuntu-latest

    # permissions must be set even when using a PAT
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false  # We will use a PAT instead

      - name: Debug PAT
        if: runner.debug
        run: |
          echo "SCORE_BOT_CLASSIC_PAT is set: [${{ secrets.SCORE_BOT_CLASSIC_PAT != '' }}]"
          echo "GITHUB_TOKEN is set: [${{ secrets.GITHUB_TOKEN != '' }}]"
        env:
          SCORE_BOT_CLASSIC_PAT: ${{ secrets.SCORE_BOT_CLASSIC_PAT }}

      - name: "Debug PAT: /user"
        if: runner.debug
        run: |
          curl -s -H "Authorization: token $SCORE_BOT_CLASSIC_PAT" https://api.github.com/user
        env:
          SCORE_BOT_CLASSIC_PAT: ${{ secrets.SCORE_BOT_CLASSIC_PAT }}

      - name: "Debug PAT: /repos/eclipse-score/bazel_registry"
        if: runner.debug
        run: |
          curl -s -H "Authorization: token $SCORE_BOT_CLASSIC_PAT" https://api.github.com/repos/eclipse-score/bazel_registry
        env:
          SCORE_BOT_CLASSIC_PAT: ${{ secrets.SCORE_BOT_CLASSIC_PAT }}

      - name: "Debug PAT: /user/repos"
        if: runner.debug
        run: |
          curl -s -H "Authorization: token $SCORE_BOT_CLASSIC_PAT" https://api.github.com/user/repos?per_page=100
        env:
          SCORE_BOT_CLASSIC_PAT: ${{ secrets.SCORE_BOT_CLASSIC_PAT }}

      - name: Run version checker script
        id: check_versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r tools/requirements.txt
          python scripts/check_and_update_modules.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update modules
          author: eclipse-score-bot <187756813+eclipse-score-bot@users.noreply.github.com>
          body: |
            This PR updates the modules to their latest versions.
            Please review and merge if everything looks good.
          commit-message: Update modules
          base: main
          branch: bot/modules-update
          token: ${{ secrets.SCORE_BOT_CLASSIC_PAT }} # PAT belongs to eclipse-score-bot
          labels: automation
