name: Pull Request Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  verify_registry:
    name: ğŸ§ª Verify Registry
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check out
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1

      - name: ğŸ”„ Cross-Check SemVer with compatibility_level
        run: |
          pip install -r tools/requirements.txt
          python tools/verify_semver_compatibility_level.py

      - name: ğŸ“‹ Run verification script
        run: bazel run //tools:verify_modules


  self_test:
    name: ğŸ”¬ Self Test
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¤ Check out
        uses: actions/checkout@v4

      - name: ğŸ§© Run pytest
        run: |
          pip install -r tools/requirements.txt
          pytest tools


  copyright-check:
    uses: eclipse-score/cicd-workflows/.github/workflows/copyright.yml@main
    with:
      bazel-target: run //tools:copyright.check
